In [2]:
import numpy as np
import pandas as pd
from model_selection import train_test_split, positive_negative_check
from sklearn import svm
from model import SVM


In [3]:
df = pd.read_csv("../archive-2/breast-cancer-wisconsin.csv")
df = df.drop(['id'], axis=1)

df = df.drop(df[df['bare_nuclei'] == '?'].index)
df['bare_nuclei'] = df['bare_nuclei'].astype(np.int64)
df

clump_thickness  uni_cell_size  uni_cell_shape  mar_adhesion  \
0                  5              1               1             1   
1                  5              4               4             5   
2                  3              1               1             1   
3                  6              8               8             1   
4                  4              1               1             3   
..               ...            ...             ...           ...   
694                3              1               1             1   
695                2              1               1             1   
696                5             10              10             3   
697                4              8               6             4   
698                4              8               8             5   

     epith_cell_size  bare_nuclei  bland_chromatin  normal_nucleoli  mitoses  \
0                  2            1                3                1        1   
1                  7           10                3                2        1   
2                  2            2                3                1        1   
3                  3            4                3                7        1   
4                  2            1                3                1        1   
..               ...          ...              ...              ...      ...   
694                3            2                1                1        1   
695                2            1                1                1        1   
696                7            3                8               10        2   
697                3            4               10                6        1   
698                4            5               10                4        1   

     class  
0        2  
1        2  
2        2  
3        2  
4        2  
..     ...  
694      2  
695      2  
696      4  
697      4  
698      4  

[683 rows x 10 columns]

In [4]:
x = np.array(df.drop(['class'], axis=1))
y = np.array(df['class'].copy())

y = np.where(y == 2, -1 , 1)

for i in x:
    print(i)

[5 1 1 1 2 1 3 1 1]
[ 5  4  4  5  7 10  3  2  1]
[3 1 1 1 2 2 3 1 1]
[6 8 8 1 3 4 3 7 1]
[4 1 1 3 2 1 3 1 1]
[ 8 10 10  8  7 10  9  7  1]
[ 1  1  1  1  2 10  3  1  1]
[2 1 2 1 2 1 3 1 1]
[2 1 1 1 2 1 1 1 5]
[4 2 1 1 2 1 2 1 1]
[1 1 1 1 1 1 3 1 1]
[2 1 1 1 2 1 2 1 1]
[5 3 3 3 2 3 4 4 1]
[1 1 1 1 2 3 3 1 1]
[ 8  7  5 10  7  9  5  5  4]
[7 4 6 4 6 1 4 3 1]
[4 1 1 1 2 1 2 1 1]
[4 1 1 1 2 1 3 1 1]
[10  7  7  6  4 10  4  1  2]
[6 1 1 1 2 1 3 1 1]
[ 7  3  2 10  5 10  5  4  4]
[10  5  5  3  6  7  7 10  1]
[3 1 1 1 2 1 2 1 1]
[1 1 1 1 2 1 3 1 1]
[5 2 3 4 2 7 3 6 1]
[3 2 1 1 1 1 2 1 1]
[5 1 1 1 2 1 2 1 1]
[2 1 1 1 2 1 2 1 1]
[1 1 3 1 2 1 1 1 1]
[3 1 1 1 1 1 2 1 1]
[2 1 1 1 2 1 3 1 1]
[10  7  7  3  8  5  7  4  3]
[2 1 1 2 2 1 3 1 1]
[3 1 2 1 2 1 2 1 1]
[2 1 1 1 2 1 2 1 1]
[10 10 10  8  6  1  8  9  1]
[6 2 1 1 1 1 7 1 1]
[ 5  4  4  9  2 10  5  6  1]
[2 5 3 3 6 7 7 5 1]
[10  4  3  1  3  3  6  5  2]
[ 6 10 10  2  8 10  7  3  3]
[ 5  6  5  6 10  1  3  1  1]
[10 10 10  4  8  1  8 10  1]
[1 1 1 1 2 1 2

In [5]:
buff_x, x_test, buff_y, y_test = train_test_split(x, y, random_state=42)
x_train, x_validate, y_train, y_validate = train_test_split(buff_x, buff_y, random_state=42)


In [6]:
model1 = svm.SVC(kernel='linear',C=100)
model1.fit(x_train, y_train)
print(model1.score(x_validate, y_validate))
print(model1.score(x_test, y_test))

1.0
0.9708029197080292


In [7]:
model2 = SVM(kernel='linear',c=100,learning_rate=0.001, lambda_param=0.001, debug=True, max_itr=2000)
model2.fit(x_train, y_train)
predict = model2.predict(x_test)
predict_validate = model2.predict(x_validate)

print(model2.score(predict_validate, y_validate))
print(model2.score(predict, y_test))

C: 100
Learning Rate: 0.001
Lambda Param: 0.001
C: 100
N_Iters: 2000
1.0
0.9854014598540146
